
server:
  port: 8081
    
logging.level:
 web: INFO
 root: INFO
 '[com.bptn]': DEBUG
 '[org.hibernate]': INFO
 '[org.hibernate.cfg.annotations.EntityBinder]': DEBUG
 '[org.springframework.beans.factory.support.DefaultListableBeanFactory]': DEBUG
 
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedApp
    username: postgres
    password: pg123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
api:
  key: 3a688ff6c8c040c1b1e6e2f38054cdcd
  base.url: https://newsapi.org/v2/everything
      